### ISSUE TITLE
Incorrect npm-shrinkwrap.json has been pushed

### ISSUE THREAD

**Issue by goremikin** [BenoitZugmeyer/eslint-plugin-html#125]
## Description

Starting with version 6.0.1 `npm-shrinkwrap.json` file has been added, which causes a lot of extraneous packages to be installed (which eventually are part of dev-dependencies, like jest).

## Setup configuration

* ESLint version: 6.8.0
* eslint-plugin-html version: 6.0.1

**Comment by BenoitZugmeyer** [comment]
Thank you for pointing this out. This is because of [a NPM change](https://github.com/npm/npm-packlist/pull/34): `npm-shrinkwrap.json` files cannot be ignored anymore. I wonder why they accepted such a breaking change without announcing it further. Anyway... I'll fix this soon.

Further details: this change have been released in `npm-packlist@1.4.5` and [npm-cli 6.12.1](https://github.com/npm/cli/blob/latest/CHANGELOG.md#6121-2019-10-29) (update to `npm-packlist@1.4.6` directly)

**Comment by BenoitZugmeyer** [comment]
Should be fixed and published in `6.0.2`! Let me know if it works for you :) Thanks again.
