### ISSUE TITLE
strict check doesn't work in HTML files with multiple <script> tags

### ISSUE THREAD

**Issue by anniesullie** [BenoitZugmeyer/eslint-plugin-html#55]
We're trying to use http://eslint.org/docs/rules/strict in conjunction with HTML files that can have multiple <script> tags. Unfortunately, this only checks one of the <script> tags; it seems they are concatenated.

**Comment by BenoitZugmeyer** [comment]
Thank you very much for the report. Scripts tag contents are indeed concatenated into one script source that is fed to eslint. I initially thought the "use strict" mode was applied on all inline script tags, but it is indeed wrong and thus each tags should be linted independently to fix this issue.

This would require a new major version to be released since it introduces breaking changes. I'll see if it is feasible.

**Comment by BenoitZugmeyer** [comment]
I released a beta version of `eslint-plugin-html`, you can test it with `npm install eslint-plugin-html@next`. I'll release a final version after `eslint 4` is released.
