### ISSUE TITLE
Warning: Unexpected token ...

### ISSUE THREAD

**Issue by jscharett** [BenoitZugmeyer/eslint-plugin-html#71]
Getting the error 'Warning: Unexpected token ... Use --force to continue' when running version 3.1.0.  Did not happen in 3.0.0.

**Comment by BenoitZugmeyer** [comment]
Could you provide a gist or something to reproduce?

**Comment by jscharett** [comment]
I will see if I can, but I'm not sure what file(s) are causing the problem.  There are hundreds of html files in the particular app I'm working on, and not sure if its something with one of them or something else.  We are using node version 4.4.3 and npm version 2.15.11 if that helps.

**Comment by hlapp** [comment]
This is caused by code in eslint-plugin-html, not code in html or other files being linted. The error happens during loading of eslint-plugin-html as an eslint plugin.

Specifically, the following line in `src/extract.js` is causing this:
```js
cdata.push(...chunks[i].cdata)
```
Apparently this was introduced in ade9021cb612f69c9c4cc1102f7b1dafcbd76566. The spread operator was [introduced in ES6](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator). It seems that nodejs 4.x doesn't support it.
